### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by KozakAG**

### CODE REVIEW

**Review by OlehKuryshko — COMMENTED** [review]
ok

**Review by vzavalskyi — COMMENTED** [review]
mega Django project

**Comment by OlehKuryshko** [comment]
123

**Review by OlehKuryshko — COMMENTED** [review]
123

**Review by vzavalskyi — CHANGES_REQUESTED** [review]
yeesss

**Review by vzavalskyi — APPROVED** [review]
Approved!

**Pull request merged**
